spring.application.name=Banking_Application
server.port = 9090

# Spring Data JPA Configuration 

spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/bank
spring.datasource.username = root
spring.datasource.password = root
spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update

#Spring Mail Configuration

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=abhijitmeher645@gmail.com
spring.mail.password=vkgb hsvs rdbd splg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

